apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sidecar-demo

resources:
  - namespace.yaml
  - services.yaml
  - networkpolicy.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - envoy-deployment.yaml
  - keycloak-deployment.yaml

configMapGenerator:
  - name: sidecar-policy
    files:
      - authz.rego=../../../sidecar/policies/authz.rego
  - name: sidecar-config
    files:
      - config.yaml=../../../sidecar/config.yaml
  - name: keycloak-realm
    files:
      - realm-export.json=../../../keycloak/realm-export.json
  - name: envoy-config
    files:
      - envoy.yaml=../../envoy/envoy.yaml

generatorOptions:
  disableNameSuffixHash: true
